### ISSUE TITLE
Navigation bar structure

### ISSUE THREAD

**Issue by ndaelman-hu** [FAIRmat-NFDI/AreaC-DOC#7]
Overall, I would keep the titles in the navigation bar short (further description can be given in their overview/intro page), and not too deeply nested (3 layers as a rule of thumb?).
Since this is the users' main navigation tool, it should be easy to skim.
More specifically, I suggest:
- _current features_ > _features_
- _custom schemas for new features_ > split it into _customization_ and _adding features_
- _defining filters for searches_ > _GUI queries_
- _querying and performing Data Science_ > _API queries_? Maybe this can be combined with _GUI queries_ under a common section _queries_? Maybe _data science_ should also be preserved, but this would be more like examples...
- _uploading and publishing data_ > _uploading & publishing_
- _visualizing properties in the entry page_ > _entries page_
- _writing a parser plugin_ > _contributing_ or _plugins_

If we have a system similar to Obsidian, we could also consider using **hashtags to mark specific files or paragraphs**, e.g. `#GUI`, `#contributing`, `#template`, etc.

**Comment by JosePizarro3** [comment]
Just closing this in favor of the gitlab issue: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/1662
